-- CREAR TABLA (CATEGORY)
CREATE TABLE ADMIN.CATEGORY (
    ID NUMBER,
    DESCRIPTION VARCHAR2(400),
    CONSTRAINT CATEGORY_ID_pk PRIMARY KEY(ID)
);


-- MANEJADOR GET
SELECT * FROM CATEGORY ORDER BY ID;


-- MANEJADOR POST
BEGIN
    INSERT INTO CATEGORY (ID, DESCRIPTION)
    VALUES (:id, :description);
    :status_code := 201;
END;


-- MANEJADOR PUT
BEGIN
    UPDATE CATEGORY
    SET 
        DESCRIPTION = :description
    WHERE
        ID = :id;
    :status_code := 201;
END;


-- MANEJADOR DELETE
BEGIN
    DELETE FROM CATEGORY WHERE ID = :id;
    :status_code := 204;
END;


-- MANEJADOR GET :id
SELECT * FROM CATEGORY WHERE ID = :id;


-- VACIAR TABLA
TRUNCATE TABLE CATEGORY;
