-- CREAR TABLA (MENSAJE)
CREATE TABLE ADMIN.MESSAGE (
    ID NUMBER,
    MESSAGETEXT VARCHAR2(4000),
    CONSTRAINT MESSAGE_ID_pk PRIMARY KEY(ID)
);


-- MANEJADOR GET
SELECT * FROM MESSAGE ORDER BY ID;


-- MANEJADOR POST
BEGIN
    INSERT INTO MESSAGE (ID, MESSAGETEXT)
    VALUES (:id, :messagetext);
    :status_code := 201;
END;


-- MANEJADOR PUT
BEGIN
    UPDATE MESSAGE
    SET 
        MESSAGETEXT = :messagetext
    WHERE
        ID = :id;
    :status_code := 201;
END;


-- MANEJADOR DELETE
BEGIN
    DELETE FROM MESSAGE WHERE ID = :id;
    :status_code := 204;
END;


-- MANEJADOR GET :id
SELECT * FROM MESSAGE WHERE ID = :id;


-- VACIAR TABLA
TRUNCATE TABLE MESSAGE;
