#MYSQL 8.0
CREATE SCHEMA `palcos` DEFAULT CHARACTER SET utf8mb4 ;

#MYSQL 5.3
CREATE DATABASE palcos CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;


#USUARIO
CREATE USER 'admin'@'%' IDENTIFIED BY 'Password123*';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%';
FLUSH PRIVILEGES;
